//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Robotics.Services.Sensors.Kinect {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Robotics.Services.Sensors.Kinect.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target acceleration specified in rotation message ignored (not supported by this service)..
        /// </summary>
        internal static string AccelerationIgnored {
            get {
                return ResourceManager.GetString("AccelerationIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Far plane distance less than zero.
        /// </summary>
        internal static string FarPlaneDistanceLessThanZero {
            get {
                return ResourceManager.GetString("FarPlaneDistanceLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field of view less than 0 or greater than 180 degrees..
        /// </summary>
        internal static string FieldOfViewOutOfRange {
            get {
                return ResourceManager.GetString("FieldOfViewOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The frame rate must be between 1 and 30..
        /// </summary>
        internal static string FrameRateOutOfRange {
            get {
                return ResourceManager.GetString("FrameRateOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing hard reset on depth camera..
        /// </summary>
        internal static string HardReset {
            get {
                return ResourceManager.GetString("HardReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid form data in HTTP Post request.
        /// </summary>
        internal static string HttpPostBadFormData {
            get {
                return ResourceManager.GetString("HttpPostBadFormData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrecognized operation in HTTP Post request : {0}.
        /// </summary>
        internal static string HttpPostUnrecognizedOperation {
            get {
                return ResourceManager.GetString("HttpPostUnrecognizedOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth camera initialized..
        /// </summary>
        internal static string Initialized {
            get {
                return ResourceManager.GetString("Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize camera, dropping service..
        /// </summary>
        internal static string InitializeFailed {
            get {
                return ResourceManager.GetString("InitializeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initializing depth camera..
        /// </summary>
        internal static string Initializing {
            get {
                return ResourceManager.GetString("Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The tilt angle must be between 30 and -30 degrees..
        /// </summary>
        internal static string InvalidTiltAngle {
            get {
                return ResourceManager.GetString("InvalidTiltAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\KinectIR.ini.
        /// </summary>
        internal static string IrIniFile {
            get {
                return ResourceManager.GetString("IrIniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near plane distance less than zero..
        /// </summary>
        internal static string NearPlaneDistanceLessThanZero {
            get {
                return ResourceManager.GetString("NearPlaneDistanceLessThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Near plane greater than or equal to far plane distance..
        /// </summary>
        internal static string NearPlaneGreaterThanOrEqualToFarPlaneDistance {
            get {
                return ResourceManager.GetString("NearPlaneGreaterThanOrEqualToFarPlaneDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 2.0 cameras are no longer supported..
        /// </summary>
        internal static string OldVersion {
            get {
                return ResourceManager.GetString("OldVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service does not support pan rotation..
        /// </summary>
        internal static string PanNotSupported {
            get {
                return ResourceManager.GetString("PanNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service does not support delaying Rotation responses until the rotation has completed..
        /// </summary>
        internal static string ResponseOnMotionCompletedNotSupported {
            get {
                return ResourceManager.GetString("ResponseOnMotionCompletedNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data\Kinect.ini.
        /// </summary>
        internal static string RgbIniFile {
            get {
                return ResourceManager.GetString("RgbIniFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing soft reset on depth camera..
        /// </summary>
        internal static string SoftReset {
            get {
                return ResourceManager.GetString("SoftReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max speed specified in rotation message ignored (not supported by this service)..
        /// </summary>
        internal static string SpeedIgnored {
            get {
                return ResourceManager.GetString("SpeedIgnored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to read a frame from the device..
        /// </summary>
        internal static string UnableToReadFrame {
            get {
                return ResourceManager.GetString("UnableToReadFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to reset depth camera..
        /// </summary>
        internal static string UnableToResetSensor {
            get {
                return ResourceManager.GetString("UnableToResetSensor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set either rate or gain..
        /// </summary>
        internal static string UnableToSetRateOrGain {
            get {
                return ResourceManager.GetString("UnableToSetRateOrGain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one attempt to update an alternate failed. .
        /// </summary>
        internal static string UpdateAlternateError {
            get {
                return ResourceManager.GetString("UpdateAlternateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service does not support the replace message on the webcam alternate contract..
        /// </summary>
        internal static string WebcamReplaceNotSupported {
            get {
                return ResourceManager.GetString("WebcamReplaceNotSupported", resourceCulture);
            }
        }
    }
}
