//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: global::System.Reflection.AssemblyProductAttribute("Wanderer")]
[assembly: global::System.Reflection.AssemblyTitleAttribute("Wanderer")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Transform, SourceAssemblyKey="Wanderer.Y2013.M02, Version=1.0.0.0, Culture=neutral, PublicKeyToken=e3a6d1d8ea72" +
    "97f8")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.SecurityRulesAttribute(global::System.Security.SecurityRuleSet.Level1)]

namespace Dss.Transforms.TransformWanderer {
    
    
    public class Transforms : global::Microsoft.Dss.Core.Transforms.TransformBase {
        
        static Transforms() {
            Register();
        }
        
        public static void Register() {
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::POFerro.Robotics.Wanderer.Proxy.WandererState), new global::Microsoft.Dss.Core.Attributes.Transform(POFerro_Robotics_Wanderer_Proxy_WandererState_TO_POFerro_Robotics_Wanderer_WandererState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::POFerro.Robotics.Wanderer.WandererState), new global::Microsoft.Dss.Core.Attributes.Transform(POFerro_Robotics_Wanderer_WandererState_TO_POFerro_Robotics_Wanderer_Proxy_WandererState));
        }
        
        private static global::POFerro.Robotics.Wanderer.Proxy.WandererState _cachedInstance0 = new global::POFerro.Robotics.Wanderer.Proxy.WandererState();
        
        private static global::POFerro.Robotics.Wanderer.WandererState _cachedInstance = new global::POFerro.Robotics.Wanderer.WandererState();
        
        public static object POFerro_Robotics_Wanderer_Proxy_WandererState_TO_POFerro_Robotics_Wanderer_WandererState(object transformFrom) {
            return _cachedInstance;
        }
        
        public static object POFerro_Robotics_Wanderer_WandererState_TO_POFerro_Robotics_Wanderer_Proxy_WandererState(object transformFrom) {
            return _cachedInstance0;
        }
    }
}
