//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: global::System.Reflection.AssemblyProductAttribute("SoundFollower")]
[assembly: global::System.Reflection.AssemblyTitleAttribute("SoundFollower")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Transform, SourceAssemblyKey="SoundFollower.Y2013.M04, Version=1.0.0.0, Culture=neutral, PublicKeyToken=e3a6d1d" +
    "8ea7297f8")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.SecurityRulesAttribute(global::System.Security.SecurityRuleSet.Level1)]

namespace Dss.Transforms.TransformSoundFollower {
    
    
    public class Transforms : global::Microsoft.Dss.Core.Transforms.TransformBase {
        
        static Transforms() {
            Register();
        }
        
        public static void Register() {
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerState), new global::Microsoft.Dss.Core.Attributes.Transform(POFerro_Robotics_SoundFollower_Proxy_SoundFollowerState_TO_POFerro_Robotics_SoundFollower_SoundFollowerState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::POFerro.Robotics.SoundFollower.SoundFollowerState), new global::Microsoft.Dss.Core.Attributes.Transform(POFerro_Robotics_SoundFollower_SoundFollowerState_TO_POFerro_Robotics_SoundFollower_Proxy_SoundFollowerState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorState), new global::Microsoft.Dss.Core.Attributes.Transform(POFerro_Robotics_SoundFollower_Proxy_EnableBehaviorState_TO_POFerro_Robotics_SoundFollower_EnableBehaviorState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::POFerro.Robotics.SoundFollower.EnableBehaviorState), new global::Microsoft.Dss.Core.Attributes.Transform(POFerro_Robotics_SoundFollower_EnableBehaviorState_TO_POFerro_Robotics_SoundFollower_Proxy_EnableBehaviorState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorChangeNotify), new global::Microsoft.Dss.Core.Attributes.Transform(POFerro_Robotics_SoundFollower_Proxy_EnableBehaviorChangeNotify_TO_POFerro_Robotics_SoundFollower_EnableBehaviorChangeNotify));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::POFerro.Robotics.SoundFollower.EnableBehaviorChangeNotify), new global::Microsoft.Dss.Core.Attributes.Transform(POFerro_Robotics_SoundFollower_EnableBehaviorChangeNotify_TO_POFerro_Robotics_SoundFollower_Proxy_EnableBehaviorChangeNotify));
        }
        
        public static object POFerro_Robotics_SoundFollower_Proxy_SoundFollowerState_TO_POFerro_Robotics_SoundFollower_SoundFollowerState(object transformFrom) {
            global::POFerro.Robotics.SoundFollower.SoundFollowerState target = new global::POFerro.Robotics.SoundFollower.SoundFollowerState();
            global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerState from = ((global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerState)(transformFrom));
            target.MinConfidenceLevel = from.MinConfidenceLevel;
            target.MaxLateralSpeed = from.MaxLateralSpeed;
            target.CurrentState = ((global::POFerro.Robotics.SoundFollower.SoundFollowerLogicalState)(((int)(from.CurrentState))));
            target.CurrentConfidenceLevel = from.CurrentConfidenceLevel;
            target.CurrentSoundAngle = from.CurrentSoundAngle;
            target.Enabled = from.Enabled;
            return target;
        }
        
        public static object POFerro_Robotics_SoundFollower_SoundFollowerState_TO_POFerro_Robotics_SoundFollower_Proxy_SoundFollowerState(object transformFrom) {
            global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerState target = new global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerState();
            global::POFerro.Robotics.SoundFollower.SoundFollowerState from = ((global::POFerro.Robotics.SoundFollower.SoundFollowerState)(transformFrom));
            target.MinConfidenceLevel = from.MinConfidenceLevel;
            target.MaxLateralSpeed = from.MaxLateralSpeed;
            target.CurrentState = ((global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerLogicalState)(((int)(from.CurrentState))));
            target.CurrentConfidenceLevel = from.CurrentConfidenceLevel;
            target.CurrentSoundAngle = from.CurrentSoundAngle;
            target.Enabled = from.Enabled;
            return target;
        }
        
        public static object POFerro_Robotics_SoundFollower_Proxy_EnableBehaviorState_TO_POFerro_Robotics_SoundFollower_EnableBehaviorState(object transformFrom) {
            global::POFerro.Robotics.SoundFollower.EnableBehaviorState target = new global::POFerro.Robotics.SoundFollower.EnableBehaviorState();
            global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorState from = ((global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorState)(transformFrom));
            target.Enabled = from.Enabled;
            return target;
        }
        
        public static object POFerro_Robotics_SoundFollower_EnableBehaviorState_TO_POFerro_Robotics_SoundFollower_Proxy_EnableBehaviorState(object transformFrom) {
            global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorState target = new global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorState();
            global::POFerro.Robotics.SoundFollower.EnableBehaviorState from = ((global::POFerro.Robotics.SoundFollower.EnableBehaviorState)(transformFrom));
            target.Enabled = from.Enabled;
            return target;
        }
        
        public static object POFerro_Robotics_SoundFollower_Proxy_EnableBehaviorChangeNotify_TO_POFerro_Robotics_SoundFollower_EnableBehaviorChangeNotify(object transformFrom) {
            global::POFerro.Robotics.SoundFollower.EnableBehaviorChangeNotify target = new global::POFerro.Robotics.SoundFollower.EnableBehaviorChangeNotify();
            global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorChangeNotify from = ((global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorChangeNotify)(transformFrom));
            target.Enabled = from.Enabled;
            return target;
        }
        
        public static object POFerro_Robotics_SoundFollower_EnableBehaviorChangeNotify_TO_POFerro_Robotics_SoundFollower_Proxy_EnableBehaviorChangeNotify(object transformFrom) {
            global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorChangeNotify target = new global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorChangeNotify();
            global::POFerro.Robotics.SoundFollower.EnableBehaviorChangeNotify from = ((global::POFerro.Robotics.SoundFollower.EnableBehaviorChangeNotify)(transformFrom));
            target.Enabled = from.Enabled;
            return target;
        }
    }
}
