//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: global::System.Reflection.AssemblyProductAttribute("SoundFollower")]
[assembly: global::System.Reflection.AssemblyTitleAttribute("SoundFollower")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Proxy, SourceAssemblyKey="SoundFollower.Y2013.M04, Version=1.0.0.0, Culture=neutral, PublicKeyToken=e3a6d1d" +
    "8ea7297f8")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.SecurityRulesAttribute(global::System.Security.SecurityRuleSet.Level1)]

namespace POFerro.Robotics.SoundFollower.Proxy {
    
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.pferro/2013/04/soundfollower.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.pferro/2013/04/soundfollower.html", ElementName="SoundFollowerState")]
    public class SoundFollowerState : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public SoundFollowerState() {
        }
        
        private double _MinConfidenceLevel;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public double MinConfidenceLevel {
            get {
                return this._MinConfidenceLevel;
            }
            set {
                this._MinConfidenceLevel = value;
            }
        }
        
        private double _MaxLateralSpeed;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public double MaxLateralSpeed {
            get {
                return this._MaxLateralSpeed;
            }
            set {
                this._MaxLateralSpeed = value;
            }
        }
        
        private global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerLogicalState _CurrentState;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerLogicalState CurrentState {
            get {
                return this._CurrentState;
            }
            set {
                this._CurrentState = value;
            }
        }
        
        private double _CurrentConfidenceLevel;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public double CurrentConfidenceLevel {
            get {
                return this._CurrentConfidenceLevel;
            }
            set {
                this._CurrentConfidenceLevel = value;
            }
        }
        
        private double _CurrentSoundAngle;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public double CurrentSoundAngle {
            get {
                return this._CurrentSoundAngle;
            }
            set {
                this._CurrentSoundAngle = value;
            }
        }
        
        private bool _Enabled;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public bool Enabled {
            get {
                return this._Enabled;
            }
            set {
                this._Enabled = value;
            }
        }
        
        /// <summary>
        ///Copies the data member values of the current SoundFollowerState to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerState typedTarget = ((global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerState)(target));
            typedTarget._MinConfidenceLevel = this._MinConfidenceLevel;
            typedTarget._MaxLateralSpeed = this._MaxLateralSpeed;
            typedTarget._CurrentState = this._CurrentState;
            typedTarget._CurrentConfidenceLevel = this._CurrentConfidenceLevel;
            typedTarget._CurrentSoundAngle = this._CurrentSoundAngle;
            typedTarget._Enabled = this._Enabled;
        }
        
        /// <summary>
        ///Clones SoundFollowerState
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerState target0 = new global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerState();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current SoundFollowerState to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
            writer.Write(this._MinConfidenceLevel);
            writer.Write(this._MaxLateralSpeed);
            writer.Write(((int)(this._CurrentState)));
            writer.Write(this._CurrentConfidenceLevel);
            writer.Write(this._CurrentSoundAngle);
            writer.Write(this._Enabled);
        }
        
        /// <summary>
        ///Deserializes SoundFollowerState
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized SoundFollowerState</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            this._MinConfidenceLevel = reader.ReadDouble();
            this._MaxLateralSpeed = reader.ReadDouble();
            this._CurrentState = ((global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerLogicalState)(reader.ReadInt32()));
            this._CurrentConfidenceLevel = reader.ReadDouble();
            this._CurrentSoundAngle = reader.ReadDouble();
            this._Enabled = reader.ReadBoolean();
            return this;
        }
    }
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.pferro/2013/04/soundfollower.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.pferro/2013/04/soundfollower.html", ElementName="EnableBehaviorState")]
    public class EnableBehaviorState : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public EnableBehaviorState() {
        }
        
        public EnableBehaviorState(bool enabled) {
            this._Enabled = enabled;
        }
        
        private bool _Enabled;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        [global::Microsoft.Dss.Core.Attributes.DataMemberConstructorAttribute(Order=1)]
        public bool Enabled {
            get {
                return this._Enabled;
            }
            set {
                this._Enabled = value;
            }
        }
        
        /// <summary>
        ///Copies the data member values of the current EnableBehaviorState to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorState typedTarget = ((global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorState)(target));
            typedTarget._Enabled = this._Enabled;
        }
        
        /// <summary>
        ///Clones EnableBehaviorState
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorState target0 = new global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorState();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current EnableBehaviorState to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
            writer.Write(this._Enabled);
        }
        
        /// <summary>
        ///Deserializes EnableBehaviorState
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized EnableBehaviorState</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            this._Enabled = reader.ReadBoolean();
            return this;
        }
    }
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.pferro/2013/04/soundfollower.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.pferro/2013/04/soundfollower.html", ElementName="EnableBehaviorChangeNotify")]
    public class EnableBehaviorChangeNotify : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public EnableBehaviorChangeNotify() {
        }
        
        public EnableBehaviorChangeNotify(bool enabled) {
            this._Enabled = enabled;
        }
        
        private bool _Enabled;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        [global::Microsoft.Dss.Core.Attributes.DataMemberConstructorAttribute(Order=1)]
        public bool Enabled {
            get {
                return this._Enabled;
            }
            set {
                this._Enabled = value;
            }
        }
        
        /// <summary>
        ///Copies the data member values of the current EnableBehaviorChangeNotify to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorChangeNotify typedTarget = ((global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorChangeNotify)(target));
            typedTarget._Enabled = this._Enabled;
        }
        
        /// <summary>
        ///Clones EnableBehaviorChangeNotify
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorChangeNotify target0 = new global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorChangeNotify();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current EnableBehaviorChangeNotify to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
            writer.Write(this._Enabled);
        }
        
        /// <summary>
        ///Deserializes EnableBehaviorChangeNotify
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized EnableBehaviorChangeNotify</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            this._Enabled = reader.ReadBoolean();
            return this;
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class Get : global::Microsoft.Dss.ServiceModel.Dssp.Get<global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType, global:: Microsoft.Ccr.Core.PortSet<global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerState, global:: W3C.Soap.Fault>> {
        
        public Get() {
        }
        
        public Get(global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body) : 
                base(body) {
        }
        
        public Get(global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body, global::Microsoft.Ccr.Core.PortSet<global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerState, global:: W3C.Soap.Fault> responsePort) : 
                base(body, responsePort) {
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class EnableBehavior : global::Microsoft.Dss.ServiceModel.Dssp.Update<global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorState, global:: Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultUpdateResponseType, global:: W3C.Soap.Fault>> {
        
        public EnableBehavior() {
        }
        
        public EnableBehavior(global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorState body) : 
                base(body) {
        }
        
        public EnableBehavior(global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorState body, global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultUpdateResponseType, global:: W3C.Soap.Fault> responsePort) : 
                base(body, responsePort) {
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class EnabledChanged : global::Microsoft.Dss.ServiceModel.Dssp.Update<global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorChangeNotify, global:: Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultUpdateResponseType, global:: W3C.Soap.Fault>> {
        
        public EnabledChanged() {
        }
        
        public EnabledChanged(global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorChangeNotify body) : 
                base(body) {
        }
        
        public EnabledChanged(global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorChangeNotify body, global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultUpdateResponseType, global:: W3C.Soap.Fault> responsePort) : 
                base(body, responsePort) {
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class StateChangeNotify : global::Microsoft.Dss.ServiceModel.Dssp.Update<global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerState, global:: Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultUpdateResponseType, global:: W3C.Soap.Fault>> {
        
        public StateChangeNotify() {
        }
        
        public StateChangeNotify(global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerState body) : 
                base(body) {
        }
        
        public StateChangeNotify(global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerState body, global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultUpdateResponseType, global:: W3C.Soap.Fault> responsePort) : 
                base(body, responsePort) {
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class Subscribe : global::Microsoft.Dss.ServiceModel.Dssp.Subscribe<global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType, global:: Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.SubscribeResponseType, global:: W3C.Soap.Fault>> {
        
        public Subscribe() {
        }
        
        public Subscribe(global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType body) : 
                base(body) {
        }
        
        public Subscribe(global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType body, global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.SubscribeResponseType, global:: W3C.Soap.Fault> responsePort) : 
                base(body, responsePort) {
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class SoundFollowerOperations : global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup, global:: Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop, global:: POFerro.Robotics.SoundFollower.Proxy.Get, global:: POFerro.Robotics.SoundFollower.Proxy.EnableBehavior, global:: POFerro.Robotics.SoundFollower.Proxy.EnabledChanged, global:: POFerro.Robotics.SoundFollower.Proxy.StateChangeNotify, global:: POFerro.Robotics.SoundFollower.Proxy.Subscribe> {
        
        public SoundFollowerOperations() {
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.LookupResponse, global::W3C.Soap.Fault> DsspDefaultLookup() {
            global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType();
            global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice DsspDefaultLookup(out global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup operation) {
            global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType();
            operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.LookupResponse, global::W3C.Soap.Fault> DsspDefaultLookup(global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType body) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType();
            }
            global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice DsspDefaultLookup(global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType body, out global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup operation) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType();
            }
            operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultDropResponseType, global::W3C.Soap.Fault> DsspDefaultDrop() {
            global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType();
            global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice DsspDefaultDrop(out global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop operation) {
            global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType();
            operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultDropResponseType, global::W3C.Soap.Fault> DsspDefaultDrop(global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType body) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType();
            }
            global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice DsspDefaultDrop(global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType body, out global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop operation) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType();
            }
            operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerState, global:: W3C.Soap.Fault> Get() {
            global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType();
            global::POFerro.Robotics.SoundFollower.Proxy.Get operation = new global::POFerro.Robotics.SoundFollower.Proxy.Get(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice Get(out global::POFerro.Robotics.SoundFollower.Proxy.Get operation) {
            global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType();
            operation = new global::POFerro.Robotics.SoundFollower.Proxy.Get(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerState, global:: W3C.Soap.Fault> Get(global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType();
            }
            global::POFerro.Robotics.SoundFollower.Proxy.Get operation = new global::POFerro.Robotics.SoundFollower.Proxy.Get(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice Get(global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType body, out global::POFerro.Robotics.SoundFollower.Proxy.Get operation) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.GetRequestType();
            }
            operation = new global::POFerro.Robotics.SoundFollower.Proxy.Get(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultUpdateResponseType, global:: W3C.Soap.Fault> EnableBehavior(bool enabled) {
            global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorState body = new global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorState(enabled);
            global::POFerro.Robotics.SoundFollower.Proxy.EnableBehavior operation = new global::POFerro.Robotics.SoundFollower.Proxy.EnableBehavior(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice EnableBehavior(bool enabled, out global::POFerro.Robotics.SoundFollower.Proxy.EnableBehavior operation) {
            global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorState body = new global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorState(enabled);
            operation = new global::POFerro.Robotics.SoundFollower.Proxy.EnableBehavior(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultUpdateResponseType, global:: W3C.Soap.Fault> EnableBehavior(global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorState body) {
            if ((body == null)) {
                body = new global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorState();
            }
            global::POFerro.Robotics.SoundFollower.Proxy.EnableBehavior operation = new global::POFerro.Robotics.SoundFollower.Proxy.EnableBehavior(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice EnableBehavior(global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorState body, out global::POFerro.Robotics.SoundFollower.Proxy.EnableBehavior operation) {
            if ((body == null)) {
                body = new global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorState();
            }
            operation = new global::POFerro.Robotics.SoundFollower.Proxy.EnableBehavior(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultUpdateResponseType, global:: W3C.Soap.Fault> EnabledChanged(bool enabled) {
            global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorChangeNotify body = new global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorChangeNotify(enabled);
            global::POFerro.Robotics.SoundFollower.Proxy.EnabledChanged operation = new global::POFerro.Robotics.SoundFollower.Proxy.EnabledChanged(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice EnabledChanged(bool enabled, out global::POFerro.Robotics.SoundFollower.Proxy.EnabledChanged operation) {
            global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorChangeNotify body = new global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorChangeNotify(enabled);
            operation = new global::POFerro.Robotics.SoundFollower.Proxy.EnabledChanged(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultUpdateResponseType, global:: W3C.Soap.Fault> EnabledChanged(global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorChangeNotify body) {
            if ((body == null)) {
                body = new global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorChangeNotify();
            }
            global::POFerro.Robotics.SoundFollower.Proxy.EnabledChanged operation = new global::POFerro.Robotics.SoundFollower.Proxy.EnabledChanged(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice EnabledChanged(global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorChangeNotify body, out global::POFerro.Robotics.SoundFollower.Proxy.EnabledChanged operation) {
            if ((body == null)) {
                body = new global::POFerro.Robotics.SoundFollower.Proxy.EnableBehaviorChangeNotify();
            }
            operation = new global::POFerro.Robotics.SoundFollower.Proxy.EnabledChanged(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultUpdateResponseType, global:: W3C.Soap.Fault> StateChangeNotify() {
            global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerState body = new global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerState();
            global::POFerro.Robotics.SoundFollower.Proxy.StateChangeNotify operation = new global::POFerro.Robotics.SoundFollower.Proxy.StateChangeNotify(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice StateChangeNotify(out global::POFerro.Robotics.SoundFollower.Proxy.StateChangeNotify operation) {
            global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerState body = new global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerState();
            operation = new global::POFerro.Robotics.SoundFollower.Proxy.StateChangeNotify(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultUpdateResponseType, global:: W3C.Soap.Fault> StateChangeNotify(global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerState body) {
            if ((body == null)) {
                body = new global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerState();
            }
            global::POFerro.Robotics.SoundFollower.Proxy.StateChangeNotify operation = new global::POFerro.Robotics.SoundFollower.Proxy.StateChangeNotify(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice StateChangeNotify(global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerState body, out global::POFerro.Robotics.SoundFollower.Proxy.StateChangeNotify operation) {
            if ((body == null)) {
                body = new global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerState();
            }
            operation = new global::POFerro.Robotics.SoundFollower.Proxy.StateChangeNotify(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.SubscribeResponseType, global:: W3C.Soap.Fault> Subscribe(global::Microsoft.Ccr.Core.IPort notificationPort, params System.Type[] types) {
            global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType();
            global::POFerro.Robotics.SoundFollower.Proxy.Subscribe operation = new global::POFerro.Robotics.SoundFollower.Proxy.Subscribe(body);
            operation.NotificationPort = notificationPort;
            if ((types != null)) {
                body.TypeFilter = new string[types.Length];
                for (int index = 0; (index < types.Length); index = (index + 1)) {
                    body.TypeFilter[index] = global::Microsoft.Dss.ServiceModel.DsspServiceBase.DsspServiceBase.GetTypeFilterDescription(types[index]);
                }
            }
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice Subscribe(global::Microsoft.Ccr.Core.IPort notificationPort, out global::POFerro.Robotics.SoundFollower.Proxy.Subscribe operation, params System.Type[] types) {
            global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType();
            operation = new global::POFerro.Robotics.SoundFollower.Proxy.Subscribe(body);
            operation.NotificationPort = notificationPort;
            if ((types != null)) {
                body.TypeFilter = new string[types.Length];
                for (int index = 0; (index < types.Length); index = (index + 1)) {
                    body.TypeFilter[index] = global::Microsoft.Dss.ServiceModel.DsspServiceBase.DsspServiceBase.GetTypeFilterDescription(types[index]);
                }
            }
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.SubscribeResponseType, global:: W3C.Soap.Fault> Subscribe(global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType body, global::Microsoft.Ccr.Core.IPort notificationPort, params System.Type[] types) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType();
            }
            global::POFerro.Robotics.SoundFollower.Proxy.Subscribe operation = new global::POFerro.Robotics.SoundFollower.Proxy.Subscribe(body);
            operation.NotificationPort = notificationPort;
            if ((types != null)) {
                body.TypeFilter = new string[types.Length];
                for (int index = 0; (index < types.Length); index = (index + 1)) {
                    body.TypeFilter[index] = global::Microsoft.Dss.ServiceModel.DsspServiceBase.DsspServiceBase.GetTypeFilterDescription(types[index]);
                }
            }
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice Subscribe(global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType body, global::Microsoft.Ccr.Core.IPort notificationPort, out global::POFerro.Robotics.SoundFollower.Proxy.Subscribe operation, params System.Type[] types) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.SubscribeRequestType();
            }
            operation = new global::POFerro.Robotics.SoundFollower.Proxy.Subscribe(body);
            operation.NotificationPort = notificationPort;
            if ((types != null)) {
                body.TypeFilter = new string[types.Length];
                for (int index = 0; (index < types.Length); index = (index + 1)) {
                    body.TypeFilter[index] = global::Microsoft.Dss.ServiceModel.DsspServiceBase.DsspServiceBase.GetTypeFilterDescription(types[index]);
                }
            }
            this.Post(operation);
            return operation.ResponsePort;
        }
    }
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.pferro/2013/04/soundfollower.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.pferro/2013/04/soundfollower.html", ElementName="SoundFollowerLogicalState")]
    public enum SoundFollowerLogicalState : int {
        
        Unknown = 0,
        
        WaitingForSound = 1,
        
        FollowingSound = 2,
        
        FacingSound = 3,
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    [global::System.ComponentModel.DescriptionAttribute("SoundFollower service (no description provided)")]
    [global::System.ComponentModel.DisplayNameAttribute("SoundFollower")]
    public class Contract {
        
        public const string Identifier = "http://schemas.pferro/2013/04/soundfollower.html";
        
        /// <summary>Creates a new instance of the service.</summary>
        /// <param name="constructorServicePort">Service constructor port</param>
        /// <param name="service">service path</param>
        /// <param name="partners">the partners of the service instance</param>
        /// <returns>create service response port</returns>
        public static global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse> CreateService(global::Microsoft.Dss.Services.Constructor.ConstructorPort constructorServicePort, string service, params Microsoft.Dss.ServiceModel.Dssp.PartnerType[] partners) {
            global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse> result = new global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse>();
            global::Microsoft.Dss.ServiceModel.Dssp.ServiceInfoType serviceInfo = new global::Microsoft.Dss.ServiceModel.Dssp.ServiceInfoType("http://schemas.pferro/2013/04/soundfollower.html", service);
            if ((partners != null)) {
                serviceInfo.PartnerList = new System.Collections.Generic.List<Microsoft.Dss.ServiceModel.Dssp.PartnerType>(partners);
            }
            global::Microsoft.Dss.Services.Constructor.Create create = new global::Microsoft.Dss.Services.Constructor.Create(serviceInfo, result);
            constructorServicePort.Post(create);
            return result;
        }
        
        /// <summary>Creates a new instance of the service.</summary>
        /// <param name="constructorServicePort">Service constructor port</param>
        /// <param name="partners">the partners of the service instance</param>
        /// <returns>create service response port</returns>
        public static global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse> CreateService(global::Microsoft.Dss.Services.Constructor.ConstructorPort constructorServicePort, params Microsoft.Dss.ServiceModel.Dssp.PartnerType[] partners) {
            global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse> result = new global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse>();
            global::Microsoft.Dss.ServiceModel.Dssp.ServiceInfoType serviceInfo = new global::Microsoft.Dss.ServiceModel.Dssp.ServiceInfoType("http://schemas.pferro/2013/04/soundfollower.html", null);
            if ((partners != null)) {
                serviceInfo.PartnerList = new System.Collections.Generic.List<Microsoft.Dss.ServiceModel.Dssp.PartnerType>(partners);
            }
            global::Microsoft.Dss.Services.Constructor.Create create = new global::Microsoft.Dss.Services.Constructor.Create(serviceInfo, result);
            constructorServicePort.Post(create);
            return result;
        }
    }
    
    public class CombinedOperationsPort : global::Microsoft.Dss.Core.DssCombinedOperationsPort {
        
        public CombinedOperationsPort() {
            this.SoundFollowerOperations = new global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerOperations();
            base.Initialize(new global::Microsoft.Dss.Core.DssOperationsPortMetadata(this.SoundFollowerOperations, "http://schemas.pferro/2013/04/soundfollower.html", "SoundFollowerOperations", ""));
        }
        
        public global::POFerro.Robotics.SoundFollower.Proxy.SoundFollowerOperations SoundFollowerOperations;
    }
}
