//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: global::System.Reflection.AssemblyProductAttribute("WandererDashboard")]
[assembly: global::System.Reflection.AssemblyTitleAttribute("WandererDashboard")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Transform, SourceAssemblyKey="WandererDashboard.Y2013.M03, Version=1.0.0.0, Culture=neutral, PublicKeyToken=e3a" +
    "6d1d8ea7297f8")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.SecurityRulesAttribute(global::System.Security.SecurityRuleSet.Level1)]

namespace Dss.Transforms.TransformWandererDashboard {
    
    
    public class Transforms : global::Microsoft.Dss.Core.Transforms.TransformBase {
        
        static Transforms() {
            Register();
        }
        
        public static void Register() {
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::POFerro.Robotics.WandererDashboard.Proxy.WandererDashboardState), new global::Microsoft.Dss.Core.Attributes.Transform(POFerro_Robotics_WandererDashboard_Proxy_WandererDashboardState_TO_POFerro_Robotics_WandererDashboard_WandererDashboardState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::POFerro.Robotics.WandererDashboard.WandererDashboardState), new global::Microsoft.Dss.Core.Attributes.Transform(POFerro_Robotics_WandererDashboard_WandererDashboardState_TO_POFerro_Robotics_WandererDashboard_Proxy_WandererDashboardState));
        }
        
        private static global::POFerro.Robotics.WandererDashboard.Proxy.WandererDashboardState _cachedInstance0 = new global::POFerro.Robotics.WandererDashboard.Proxy.WandererDashboardState();
        
        private static global::POFerro.Robotics.WandererDashboard.WandererDashboardState _cachedInstance = new global::POFerro.Robotics.WandererDashboard.WandererDashboardState();
        
        public static object POFerro_Robotics_WandererDashboard_Proxy_WandererDashboardState_TO_POFerro_Robotics_WandererDashboard_WandererDashboardState(object transformFrom) {
            return _cachedInstance;
        }
        
        public static object POFerro_Robotics_WandererDashboard_WandererDashboardState_TO_POFerro_Robotics_WandererDashboard_Proxy_WandererDashboardState(object transformFrom) {
            return _cachedInstance0;
        }
    }
}
