//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("0.0.0.0")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Proxy, SourceAssemblyKey="POFerro.Robotics.GameController.Y2006.M09, Version=0.0.0.0, Culture=neutral, Publ" +
    "icKeyToken=e3a6d1d8ea7297f8")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.SecurityRulesAttribute(global::System.Security.SecurityRuleSet.Level1)]

namespace POFerro.Robotics.GameController.Proxy {
    
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.pferro/robotics/2013/04/gamecontroller.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.pferro/robotics/2013/04/gamecontroller.html", ElementName="GameControllerState")]
    public class GameControllerState : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public GameControllerState() {
        }
        
        private global::System.DateTime _TimeStamp;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.DateTime TimeStamp {
            get {
                return this._TimeStamp;
            }
            set {
                this._TimeStamp = value;
            }
        }
        
        private global::POFerro.Robotics.GameController.Proxy.Controller _Controller = new global::POFerro.Robotics.GameController.Proxy.Controller();
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(IsRequired=true, Order=-1)]
        public global::POFerro.Robotics.GameController.Proxy.Controller Controller {
            get {
                return this._Controller;
            }
            set {
                this._Controller = value;
            }
        }
        
        private global::POFerro.Robotics.GameController.Proxy.Axes _Axes = new global::POFerro.Robotics.GameController.Proxy.Axes();
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(IsRequired=true, Order=-1)]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::POFerro.Robotics.GameController.Proxy.Axes Axes {
            get {
                return this._Axes;
            }
            set {
                this._Axes = value;
            }
        }
        
        private global::POFerro.Robotics.GameController.Proxy.Buttons _Buttons = new global::POFerro.Robotics.GameController.Proxy.Buttons();
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(IsRequired=true, Order=-1)]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::POFerro.Robotics.GameController.Proxy.Buttons Buttons {
            get {
                return this._Buttons;
            }
            set {
                this._Buttons = value;
            }
        }
        
        private global::POFerro.Robotics.GameController.Proxy.Sliders _Sliders = new global::POFerro.Robotics.GameController.Proxy.Sliders();
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(IsRequired=true, Order=-1)]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::POFerro.Robotics.GameController.Proxy.Sliders Sliders {
            get {
                return this._Sliders;
            }
            set {
                this._Sliders = value;
            }
        }
        
        private global::POFerro.Robotics.GameController.Proxy.PovHats _PovHats = new global::POFerro.Robotics.GameController.Proxy.PovHats();
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(IsRequired=true, Order=-1)]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::POFerro.Robotics.GameController.Proxy.PovHats PovHats {
            get {
                return this._PovHats;
            }
            set {
                this._PovHats = value;
            }
        }
        
        /// <summary>
        ///Copies the data member values of the current GameControllerState to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::POFerro.Robotics.GameController.Proxy.GameControllerState typedTarget = ((global::POFerro.Robotics.GameController.Proxy.GameControllerState)(target));
            typedTarget._TimeStamp = this._TimeStamp;
            if ((this._Controller != null)) {
                global::POFerro.Robotics.GameController.Proxy.Controller tmp = new global::POFerro.Robotics.GameController.Proxy.Controller();
                ((Microsoft.Dss.Core.IDssSerializable)(this._Controller)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp)));
                typedTarget._Controller = tmp;
            }
            if ((this._Axes != null)) {
                global::POFerro.Robotics.GameController.Proxy.Axes tmp0 = new global::POFerro.Robotics.GameController.Proxy.Axes();
                ((Microsoft.Dss.Core.IDssSerializable)(this._Axes)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp0)));
                typedTarget._Axes = tmp0;
            }
            if ((this._Buttons != null)) {
                global::POFerro.Robotics.GameController.Proxy.Buttons tmp1 = new global::POFerro.Robotics.GameController.Proxy.Buttons();
                ((Microsoft.Dss.Core.IDssSerializable)(this._Buttons)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp1)));
                typedTarget._Buttons = tmp1;
            }
            if ((this._Sliders != null)) {
                global::POFerro.Robotics.GameController.Proxy.Sliders tmp2 = new global::POFerro.Robotics.GameController.Proxy.Sliders();
                ((Microsoft.Dss.Core.IDssSerializable)(this._Sliders)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp2)));
                typedTarget._Sliders = tmp2;
            }
            if ((this._PovHats != null)) {
                global::POFerro.Robotics.GameController.Proxy.PovHats tmp3 = new global::POFerro.Robotics.GameController.Proxy.PovHats();
                ((Microsoft.Dss.Core.IDssSerializable)(this._PovHats)).CopyTo(((Microsoft.Dss.Core.IDssSerializable)(tmp3)));
                typedTarget._PovHats = tmp3;
            }
        }
        
        /// <summary>
        ///Clones GameControllerState
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::POFerro.Robotics.GameController.Proxy.GameControllerState target0 = new global::POFerro.Robotics.GameController.Proxy.GameControllerState();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current GameControllerState to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
            global::Microsoft.Dss.Services.Serializer.BinarySerializationHelper.SerializeDateTime(this._TimeStamp, writer);
            if ((this._Controller == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                ((Microsoft.Dss.Core.IDssSerializable)(this._Controller)).Serialize(writer);
            }
            if ((this._Axes == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                ((Microsoft.Dss.Core.IDssSerializable)(this._Axes)).Serialize(writer);
            }
            if ((this._Buttons == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                ((Microsoft.Dss.Core.IDssSerializable)(this._Buttons)).Serialize(writer);
            }
            if ((this._Sliders == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                ((Microsoft.Dss.Core.IDssSerializable)(this._Sliders)).Serialize(writer);
            }
            if ((this._PovHats == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                ((Microsoft.Dss.Core.IDssSerializable)(this._PovHats)).Serialize(writer);
            }
        }
        
        /// <summary>
        ///Deserializes GameControllerState
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized GameControllerState</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            this._TimeStamp = global::Microsoft.Dss.Services.Serializer.BinarySerializationHelper.DeserializeDateTime(reader);
            if ((reader.ReadByte() != 0)) {
                this._Controller = ((global::POFerro.Robotics.GameController.Proxy.Controller)(((Microsoft.Dss.Core.IDssSerializable)(new global::POFerro.Robotics.GameController.Proxy.Controller())).Deserialize(reader)));
            }
            if ((reader.ReadByte() != 0)) {
                this._Axes = ((global::POFerro.Robotics.GameController.Proxy.Axes)(((Microsoft.Dss.Core.IDssSerializable)(new global::POFerro.Robotics.GameController.Proxy.Axes())).Deserialize(reader)));
            }
            if ((reader.ReadByte() != 0)) {
                this._Buttons = ((global::POFerro.Robotics.GameController.Proxy.Buttons)(((Microsoft.Dss.Core.IDssSerializable)(new global::POFerro.Robotics.GameController.Proxy.Buttons())).Deserialize(reader)));
            }
            if ((reader.ReadByte() != 0)) {
                this._Sliders = ((global::POFerro.Robotics.GameController.Proxy.Sliders)(((Microsoft.Dss.Core.IDssSerializable)(new global::POFerro.Robotics.GameController.Proxy.Sliders())).Deserialize(reader)));
            }
            if ((reader.ReadByte() != 0)) {
                this._PovHats = ((global::POFerro.Robotics.GameController.Proxy.PovHats)(((Microsoft.Dss.Core.IDssSerializable)(new global::POFerro.Robotics.GameController.Proxy.PovHats())).Deserialize(reader)));
            }
            return this;
        }
    }
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.pferro/robotics/2013/04/gamecontroller.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.pferro/robotics/2013/04/gamecontroller.html", ElementName="Controller")]
    public class Controller : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public Controller() {
        }
        
        private global::System.DateTime _TimeStamp;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.DateTime TimeStamp {
            get {
                return this._TimeStamp;
            }
            set {
                this._TimeStamp = value;
            }
        }
        
        private global::System.Guid _Instance;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Guid Instance {
            get {
                return this._Instance;
            }
            set {
                this._Instance = value;
            }
        }
        
        private global::System.Guid _Product;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public global::System.Guid Product {
            get {
                return this._Product;
            }
            set {
                this._Product = value;
            }
        }
        
        private string _InstanceName;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public string InstanceName {
            get {
                return this._InstanceName;
            }
            set {
                this._InstanceName = value;
            }
        }
        
        private string _ProductName;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public string ProductName {
            get {
                return this._ProductName;
            }
            set {
                this._ProductName = value;
            }
        }
        
        private bool _Current;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public bool Current {
            get {
                return this._Current;
            }
            set {
                this._Current = value;
            }
        }
        
        /// <summary>
        ///Copies the data member values of the current Controller to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::POFerro.Robotics.GameController.Proxy.Controller typedTarget = ((global::POFerro.Robotics.GameController.Proxy.Controller)(target));
            typedTarget._TimeStamp = this._TimeStamp;
            typedTarget._Instance = this._Instance;
            typedTarget._Product = this._Product;
            typedTarget._InstanceName = this._InstanceName;
            typedTarget._ProductName = this._ProductName;
            typedTarget._Current = this._Current;
        }
        
        /// <summary>
        ///Clones Controller
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::POFerro.Robotics.GameController.Proxy.Controller target0 = new global::POFerro.Robotics.GameController.Proxy.Controller();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current Controller to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
            global::Microsoft.Dss.Services.Serializer.BinarySerializationHelper.SerializeDateTime(this._TimeStamp, writer);
            global::Microsoft.Dss.Services.Serializer.BinarySerializationHelper.SerializeAsXml(writer, this._Instance);
            global::Microsoft.Dss.Services.Serializer.BinarySerializationHelper.SerializeAsXml(writer, this._Product);
            if ((this._InstanceName == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                writer.Write(this._InstanceName);
            }
            if ((this._ProductName == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                writer.Write(this._ProductName);
            }
            writer.Write(this._Current);
        }
        
        /// <summary>
        ///Deserializes Controller
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized Controller</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            this._TimeStamp = global::Microsoft.Dss.Services.Serializer.BinarySerializationHelper.DeserializeDateTime(reader);
            this._Instance = ((global::System.Guid)(global::Microsoft.Dss.Services.Serializer.BinarySerializationHelper.DeserializeXml(reader, typeof(global::System.Guid))));
            this._Product = ((global::System.Guid)(global::Microsoft.Dss.Services.Serializer.BinarySerializationHelper.DeserializeXml(reader, typeof(global::System.Guid))));
            if ((reader.ReadByte() != 0)) {
                this._InstanceName = reader.ReadString();
            }
            if ((reader.ReadByte() != 0)) {
                this._ProductName = reader.ReadString();
            }
            this._Current = reader.ReadBoolean();
            return this;
        }
    }
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.pferro/robotics/2013/04/gamecontroller.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.pferro/robotics/2013/04/gamecontroller.html", ElementName="Axes")]
    public class Axes : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public Axes() {
        }
        
        private global::System.DateTime _TimeStamp;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public global::System.DateTime TimeStamp {
            get {
                return this._TimeStamp;
            }
            set {
                this._TimeStamp = value;
            }
        }
        
        private int _X;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public int X {
            get {
                return this._X;
            }
            set {
                this._X = value;
            }
        }
        
        private int _Y;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public int Y {
            get {
                return this._Y;
            }
            set {
                this._Y = value;
            }
        }
        
        private int _Z;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public int Z {
            get {
                return this._Z;
            }
            set {
                this._Z = value;
            }
        }
        
        private int _Rx;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public int Rx {
            get {
                return this._Rx;
            }
            set {
                this._Rx = value;
            }
        }
        
        private int _Ry;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public int Ry {
            get {
                return this._Ry;
            }
            set {
                this._Ry = value;
            }
        }
        
        private int _Rz;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public int Rz {
            get {
                return this._Rz;
            }
            set {
                this._Rz = value;
            }
        }
        
        /// <summary>
        ///Copies the data member values of the current Axes to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::POFerro.Robotics.GameController.Proxy.Axes typedTarget = ((global::POFerro.Robotics.GameController.Proxy.Axes)(target));
            typedTarget._TimeStamp = this._TimeStamp;
            typedTarget._X = this._X;
            typedTarget._Y = this._Y;
            typedTarget._Z = this._Z;
            typedTarget._Rx = this._Rx;
            typedTarget._Ry = this._Ry;
            typedTarget._Rz = this._Rz;
        }
        
        /// <summary>
        ///Clones Axes
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::POFerro.Robotics.GameController.Proxy.Axes target0 = new global::POFerro.Robotics.GameController.Proxy.Axes();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current Axes to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
            global::Microsoft.Dss.Services.Serializer.BinarySerializationHelper.SerializeDateTime(this._TimeStamp, writer);
            writer.Write(this._X);
            writer.Write(this._Y);
            writer.Write(this._Z);
            writer.Write(this._Rx);
            writer.Write(this._Ry);
            writer.Write(this._Rz);
        }
        
        /// <summary>
        ///Deserializes Axes
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized Axes</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            this._TimeStamp = global::Microsoft.Dss.Services.Serializer.BinarySerializationHelper.DeserializeDateTime(reader);
            this._X = reader.ReadInt32();
            this._Y = reader.ReadInt32();
            this._Z = reader.ReadInt32();
            this._Rx = reader.ReadInt32();
            this._Ry = reader.ReadInt32();
            this._Rz = reader.ReadInt32();
            return this;
        }
    }
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.pferro/robotics/2013/04/gamecontroller.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.pferro/robotics/2013/04/gamecontroller.html", ElementName="Buttons")]
    public class Buttons : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public Buttons() {
        }
        
        private global::System.DateTime _TimeStamp;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public global::System.DateTime TimeStamp {
            get {
                return this._TimeStamp;
            }
            set {
                this._TimeStamp = value;
            }
        }
        
        private global::System.Collections.Generic.List<bool> _Pressed = new global::System.Collections.Generic.List<bool>();
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(IsRequired=true, Order=-1)]
        public global::System.Collections.Generic.List<bool> Pressed {
            get {
                return this._Pressed;
            }
            set {
                this._Pressed = value;
            }
        }
        
        /// <summary>
        ///Copies the data member values of the current Buttons to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::POFerro.Robotics.GameController.Proxy.Buttons typedTarget = ((global::POFerro.Robotics.GameController.Proxy.Buttons)(target));
            typedTarget._TimeStamp = this._TimeStamp;
            if ((this._Pressed != null)) {
                int count = this._Pressed.Count;
                global::System.Collections.Generic.List<bool> tmp = new global::System.Collections.Generic.List<bool>(count);
                tmp.AddRange(this._Pressed);
                typedTarget._Pressed = tmp;
            }
        }
        
        /// <summary>
        ///Clones Buttons
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::POFerro.Robotics.GameController.Proxy.Buttons target0 = new global::POFerro.Robotics.GameController.Proxy.Buttons();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current Buttons to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
            global::Microsoft.Dss.Services.Serializer.BinarySerializationHelper.SerializeDateTime(this._TimeStamp, writer);
            if ((this._Pressed == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                writer.Write(this._Pressed.Count);
                for (int indexPressed = 0; (indexPressed < this._Pressed.Count); indexPressed = (indexPressed + 1)) {
                    writer.Write(this._Pressed[indexPressed]);
                }
            }
        }
        
        /// <summary>
        ///Deserializes Buttons
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized Buttons</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            this._TimeStamp = global::Microsoft.Dss.Services.Serializer.BinarySerializationHelper.DeserializeDateTime(reader);
            if ((reader.ReadByte() != 0)) {
                int count0 = reader.ReadInt32();
                this._Pressed = new global::System.Collections.Generic.List<bool>(count0);
                for (int index = 0; (index < count0); index = (index + 1)) {
                    this._Pressed.Add(default(bool));
                    this._Pressed[index] = reader.ReadBoolean();
                }
            }
            return this;
        }
    }
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.pferro/robotics/2013/04/gamecontroller.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.pferro/robotics/2013/04/gamecontroller.html", ElementName="Sliders")]
    public class Sliders : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public Sliders() {
        }
        
        private global::System.DateTime _TimeStamp;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public global::System.DateTime TimeStamp {
            get {
                return this._TimeStamp;
            }
            set {
                this._TimeStamp = value;
            }
        }
        
        private global::System.Collections.Generic.List<int> _Position = new global::System.Collections.Generic.List<int>();
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(IsRequired=true, Order=-1)]
        public global::System.Collections.Generic.List<int> Position {
            get {
                return this._Position;
            }
            set {
                this._Position = value;
            }
        }
        
        /// <summary>
        ///Copies the data member values of the current Sliders to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::POFerro.Robotics.GameController.Proxy.Sliders typedTarget = ((global::POFerro.Robotics.GameController.Proxy.Sliders)(target));
            typedTarget._TimeStamp = this._TimeStamp;
            if ((this._Position != null)) {
                int count = this._Position.Count;
                global::System.Collections.Generic.List<int> tmp = new global::System.Collections.Generic.List<int>(count);
                tmp.AddRange(this._Position);
                typedTarget._Position = tmp;
            }
        }
        
        /// <summary>
        ///Clones Sliders
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::POFerro.Robotics.GameController.Proxy.Sliders target0 = new global::POFerro.Robotics.GameController.Proxy.Sliders();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current Sliders to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
            global::Microsoft.Dss.Services.Serializer.BinarySerializationHelper.SerializeDateTime(this._TimeStamp, writer);
            if ((this._Position == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                writer.Write(this._Position.Count);
                for (int indexPosition = 0; (indexPosition < this._Position.Count); indexPosition = (indexPosition + 1)) {
                    writer.Write(this._Position[indexPosition]);
                }
            }
        }
        
        /// <summary>
        ///Deserializes Sliders
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized Sliders</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            this._TimeStamp = global::Microsoft.Dss.Services.Serializer.BinarySerializationHelper.DeserializeDateTime(reader);
            if ((reader.ReadByte() != 0)) {
                int count0 = reader.ReadInt32();
                this._Position = new global::System.Collections.Generic.List<int>(count0);
                for (int index = 0; (index < count0); index = (index + 1)) {
                    this._Position.Add(default(int));
                    this._Position[index] = reader.ReadInt32();
                }
            }
            return this;
        }
    }
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.pferro/robotics/2013/04/gamecontroller.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.pferro/robotics/2013/04/gamecontroller.html", ElementName="PovHats")]
    public class PovHats : global::Microsoft.Dss.Core.IDssSerializable, global::System.ICloneable {
        
        public PovHats() {
        }
        
        private global::System.DateTime _TimeStamp;
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(Order=-1)]
        public global::System.DateTime TimeStamp {
            get {
                return this._TimeStamp;
            }
            set {
                this._TimeStamp = value;
            }
        }
        
        private global::System.Collections.Generic.List<int> _Direction = new global::System.Collections.Generic.List<int>();
        
        [global::Microsoft.Dss.Core.Attributes.DataMemberAttribute(IsRequired=true, Order=-1)]
        public global::System.Collections.Generic.List<int> Direction {
            get {
                return this._Direction;
            }
            set {
                this._Direction = value;
            }
        }
        
        /// <summary>
        ///Copies the data member values of the current PovHats to the specified target object
        ///</summary>
        ///<param name="target">target object (must be an instance of)</param>
        public virtual void CopyTo(Microsoft.Dss.Core.IDssSerializable target) {
            global::POFerro.Robotics.GameController.Proxy.PovHats typedTarget = ((global::POFerro.Robotics.GameController.Proxy.PovHats)(target));
            typedTarget._TimeStamp = this._TimeStamp;
            if ((this._Direction != null)) {
                int count = this._Direction.Count;
                global::System.Collections.Generic.List<int> tmp = new global::System.Collections.Generic.List<int>(count);
                tmp.AddRange(this._Direction);
                typedTarget._Direction = tmp;
            }
        }
        
        /// <summary>
        ///Clones PovHats
        ///</summary>
        ///<returns>cloned value</returns>
        public virtual object Clone() {
            global::POFerro.Robotics.GameController.Proxy.PovHats target0 = new global::POFerro.Robotics.GameController.Proxy.PovHats();
            this.CopyTo(target0);
            return target0;
        }
        
        /// <summary>
        ///Serializes the data member values of the current PovHats to the specified writer
        ///</summary>
        ///<param name="writer">the writer to which to serialize</param>
        public virtual void Serialize(System.IO.BinaryWriter writer) {
            global::Microsoft.Dss.Services.Serializer.BinarySerializationHelper.SerializeDateTime(this._TimeStamp, writer);
            if ((this._Direction == null)) {
                writer.Write(((byte)(0)));
            }
            else {
                writer.Write(((byte)(1)));
                writer.Write(this._Direction.Count);
                for (int indexDirection = 0; (indexDirection < this._Direction.Count); indexDirection = (indexDirection + 1)) {
                    writer.Write(this._Direction[indexDirection]);
                }
            }
        }
        
        /// <summary>
        ///Deserializes PovHats
        ///</summary>
        ///<param name="reader">the reader from which to deserialize</param>
        ///<returns>deserialized PovHats</returns>
        public virtual object Deserialize(System.IO.BinaryReader reader) {
            this._TimeStamp = global::Microsoft.Dss.Services.Serializer.BinarySerializationHelper.DeserializeDateTime(reader);
            if ((reader.ReadByte() != 0)) {
                int count0 = reader.ReadInt32();
                this._Direction = new global::System.Collections.Generic.List<int>(count0);
                for (int index = 0; (index < count0); index = (index + 1)) {
                    this._Direction.Add(default(int));
                    this._Direction[index] = reader.ReadInt32();
                }
            }
            return this;
        }
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    public class GameControllerOperations : global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup, global:: Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop> {
        
        public GameControllerOperations() {
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.LookupResponse, global::W3C.Soap.Fault> DsspDefaultLookup() {
            global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType();
            global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice DsspDefaultLookup(out global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup operation) {
            global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType();
            operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.LookupResponse, global::W3C.Soap.Fault> DsspDefaultLookup(global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType body) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType();
            }
            global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice DsspDefaultLookup(global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType body, out global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup operation) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.LookupRequestType();
            }
            operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultLookup(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultDropResponseType, global::W3C.Soap.Fault> DsspDefaultDrop() {
            global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType();
            global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice DsspDefaultDrop(out global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop operation) {
            global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType body = new global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType();
            operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.PortSet<global::Microsoft.Dss.ServiceModel.Dssp.DefaultDropResponseType, global::W3C.Soap.Fault> DsspDefaultDrop(global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType body) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType();
            }
            global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
        
        public virtual global::Microsoft.Ccr.Core.Choice DsspDefaultDrop(global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType body, out global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop operation) {
            if ((body == null)) {
                body = new global::Microsoft.Dss.ServiceModel.Dssp.DropRequestType();
            }
            operation = new global::Microsoft.Dss.ServiceModel.Dssp.DsspDefaultDrop(body);
            this.Post(operation);
            return operation.ResponsePort;
        }
    }
    
    [global::Microsoft.Dss.Core.Attributes.DataContractAttribute(Namespace="http://schemas.pferro/robotics/2013/04/gamecontroller.html")]
    [global::System.Xml.Serialization.XmlRootAttribute(Namespace="http://schemas.pferro/robotics/2013/04/gamecontroller.html", ElementName="Substate")]
    [global::System.FlagsAttribute()]
    public enum Substate : int {
        
        None = 0,
        
        Controller = 1,
        
        Axes = 2,
        
        Buttons = 4,
        
        Sliders = 8,
        
        PovHats = 16,
    }
    
    [global::System.Xml.Serialization.XmlTypeAttribute(IncludeInSchema=false)]
    [global::System.ComponentModel.DisplayNameAttribute("Fake Game Controller")]
    public class Contract {
        
        public const string Identifier = "http://schemas.pferro/robotics/2013/04/gamecontroller.html";
        
        /// <summary>Creates a new instance of the service.</summary>
        /// <param name="constructorServicePort">Service constructor port</param>
        /// <param name="service">service path</param>
        /// <param name="partners">the partners of the service instance</param>
        /// <returns>create service response port</returns>
        public static global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse> CreateService(global::Microsoft.Dss.Services.Constructor.ConstructorPort constructorServicePort, string service, params Microsoft.Dss.ServiceModel.Dssp.PartnerType[] partners) {
            global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse> result = new global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse>();
            global::Microsoft.Dss.ServiceModel.Dssp.ServiceInfoType serviceInfo = new global::Microsoft.Dss.ServiceModel.Dssp.ServiceInfoType("http://schemas.pferro/robotics/2013/04/gamecontroller.html", service);
            if ((partners != null)) {
                serviceInfo.PartnerList = new System.Collections.Generic.List<Microsoft.Dss.ServiceModel.Dssp.PartnerType>(partners);
            }
            global::Microsoft.Dss.Services.Constructor.Create create = new global::Microsoft.Dss.Services.Constructor.Create(serviceInfo, result);
            constructorServicePort.Post(create);
            return result;
        }
        
        /// <summary>Creates a new instance of the service.</summary>
        /// <param name="constructorServicePort">Service constructor port</param>
        /// <param name="partners">the partners of the service instance</param>
        /// <returns>create service response port</returns>
        public static global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse> CreateService(global::Microsoft.Dss.Services.Constructor.ConstructorPort constructorServicePort, params Microsoft.Dss.ServiceModel.Dssp.PartnerType[] partners) {
            global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse> result = new global::Microsoft.Dss.ServiceModel.Dssp.DsspResponsePort<Microsoft.Dss.ServiceModel.Dssp.CreateResponse>();
            global::Microsoft.Dss.ServiceModel.Dssp.ServiceInfoType serviceInfo = new global::Microsoft.Dss.ServiceModel.Dssp.ServiceInfoType("http://schemas.pferro/robotics/2013/04/gamecontroller.html", null);
            if ((partners != null)) {
                serviceInfo.PartnerList = new System.Collections.Generic.List<Microsoft.Dss.ServiceModel.Dssp.PartnerType>(partners);
            }
            global::Microsoft.Dss.Services.Constructor.Create create = new global::Microsoft.Dss.Services.Constructor.Create(serviceInfo, result);
            constructorServicePort.Post(create);
            return result;
        }
    }
    
    public class CombinedOperationsPort : global::Microsoft.Dss.Core.DssCombinedOperationsPort {
        
        public CombinedOperationsPort() {
            this.GameControllerOperations = new global::POFerro.Robotics.GameController.Proxy.GameControllerOperations();
            this.UserGameControllerY2006M09GameControllerOperations = new global::Microsoft.Robotics.Services.GameController.Proxy.GameControllerOperations();
            base.Initialize(new global::Microsoft.Dss.Core.DssOperationsPortMetadata(this.GameControllerOperations, "http://schemas.pferro/robotics/2013/04/gamecontroller.html", "GameControllerOperations", ""), new global::Microsoft.Dss.Core.DssOperationsPortMetadata(this.UserGameControllerY2006M09GameControllerOperations, "http://schemas.microsoft.com/robotics/2006/09/gamecontroller.user.html", "UserGameControllerY2006M09GameControllerOperations", null));
        }
        
        public global::POFerro.Robotics.GameController.Proxy.GameControllerOperations GameControllerOperations;
        
        public global::Microsoft.Robotics.Services.GameController.Proxy.GameControllerOperations UserGameControllerY2006M09GameControllerOperations;
    }
}
