//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("0.0.0.0")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Transform, SourceAssemblyKey="POFerro.Robotics.GameController.Y2006.M09, Version=0.0.0.0, Culture=neutral, Publ" +
    "icKeyToken=e3a6d1d8ea7297f8")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.SecurityRulesAttribute(global::System.Security.SecurityRuleSet.Level1)]

namespace Dss.Transforms.TransformPOFerro {
    
    
    public class Transforms : global::Microsoft.Dss.Core.Transforms.TransformBase {
        
        static Transforms() {
            Register();
        }
        
        public static void Register() {
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::POFerro.Robotics.GameController.Proxy.GameControllerState), new global::Microsoft.Dss.Core.Attributes.Transform(POFerro_Robotics_GameController_Proxy_GameControllerState_TO_POFerro_Robotics_GameController_GameControllerState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::POFerro.Robotics.GameController.GameControllerState), new global::Microsoft.Dss.Core.Attributes.Transform(POFerro_Robotics_GameController_GameControllerState_TO_POFerro_Robotics_GameController_Proxy_GameControllerState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::POFerro.Robotics.GameController.Proxy.Controller), new global::Microsoft.Dss.Core.Attributes.Transform(POFerro_Robotics_GameController_Proxy_Controller_TO_POFerro_Robotics_GameController_Controller));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::POFerro.Robotics.GameController.Controller), new global::Microsoft.Dss.Core.Attributes.Transform(POFerro_Robotics_GameController_Controller_TO_POFerro_Robotics_GameController_Proxy_Controller));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::POFerro.Robotics.GameController.Proxy.Axes), new global::Microsoft.Dss.Core.Attributes.Transform(POFerro_Robotics_GameController_Proxy_Axes_TO_POFerro_Robotics_GameController_Axes));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::POFerro.Robotics.GameController.Axes), new global::Microsoft.Dss.Core.Attributes.Transform(POFerro_Robotics_GameController_Axes_TO_POFerro_Robotics_GameController_Proxy_Axes));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::POFerro.Robotics.GameController.Proxy.Buttons), new global::Microsoft.Dss.Core.Attributes.Transform(POFerro_Robotics_GameController_Proxy_Buttons_TO_POFerro_Robotics_GameController_Buttons));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::POFerro.Robotics.GameController.Buttons), new global::Microsoft.Dss.Core.Attributes.Transform(POFerro_Robotics_GameController_Buttons_TO_POFerro_Robotics_GameController_Proxy_Buttons));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::POFerro.Robotics.GameController.Proxy.Sliders), new global::Microsoft.Dss.Core.Attributes.Transform(POFerro_Robotics_GameController_Proxy_Sliders_TO_POFerro_Robotics_GameController_Sliders));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::POFerro.Robotics.GameController.Sliders), new global::Microsoft.Dss.Core.Attributes.Transform(POFerro_Robotics_GameController_Sliders_TO_POFerro_Robotics_GameController_Proxy_Sliders));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::POFerro.Robotics.GameController.Proxy.PovHats), new global::Microsoft.Dss.Core.Attributes.Transform(POFerro_Robotics_GameController_Proxy_PovHats_TO_POFerro_Robotics_GameController_PovHats));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::POFerro.Robotics.GameController.PovHats), new global::Microsoft.Dss.Core.Attributes.Transform(POFerro_Robotics_GameController_PovHats_TO_POFerro_Robotics_GameController_Proxy_PovHats));
        }
        
        public static object POFerro_Robotics_GameController_Proxy_GameControllerState_TO_POFerro_Robotics_GameController_GameControllerState(object transformFrom) {
            global::POFerro.Robotics.GameController.GameControllerState target = new global::POFerro.Robotics.GameController.GameControllerState();
            global::POFerro.Robotics.GameController.Proxy.GameControllerState from = ((global::POFerro.Robotics.GameController.Proxy.GameControllerState)(transformFrom));
            target.TimeStamp = from.TimeStamp;
            if ((from.Controller != null)) {
                target.Controller = ((global::POFerro.Robotics.GameController.Controller)(POFerro_Robotics_GameController_Proxy_Controller_TO_POFerro_Robotics_GameController_Controller(from.Controller)));
            }
            else {
                target.Controller = null;
            }
            if ((from.Axes != null)) {
                target.Axes = ((global::POFerro.Robotics.GameController.Axes)(POFerro_Robotics_GameController_Proxy_Axes_TO_POFerro_Robotics_GameController_Axes(from.Axes)));
            }
            else {
                target.Axes = null;
            }
            if ((from.Buttons != null)) {
                target.Buttons = ((global::POFerro.Robotics.GameController.Buttons)(POFerro_Robotics_GameController_Proxy_Buttons_TO_POFerro_Robotics_GameController_Buttons(from.Buttons)));
            }
            else {
                target.Buttons = null;
            }
            if ((from.Sliders != null)) {
                target.Sliders = ((global::POFerro.Robotics.GameController.Sliders)(POFerro_Robotics_GameController_Proxy_Sliders_TO_POFerro_Robotics_GameController_Sliders(from.Sliders)));
            }
            else {
                target.Sliders = null;
            }
            if ((from.PovHats != null)) {
                target.PovHats = ((global::POFerro.Robotics.GameController.PovHats)(POFerro_Robotics_GameController_Proxy_PovHats_TO_POFerro_Robotics_GameController_PovHats(from.PovHats)));
            }
            else {
                target.PovHats = null;
            }
            return target;
        }
        
        public static object POFerro_Robotics_GameController_GameControllerState_TO_POFerro_Robotics_GameController_Proxy_GameControllerState(object transformFrom) {
            global::POFerro.Robotics.GameController.Proxy.GameControllerState target = new global::POFerro.Robotics.GameController.Proxy.GameControllerState();
            global::POFerro.Robotics.GameController.GameControllerState from = ((global::POFerro.Robotics.GameController.GameControllerState)(transformFrom));
            target.TimeStamp = from.TimeStamp;
            global::POFerro.Robotics.GameController.Controller tmp = from.Controller;
            if ((tmp != null)) {
                target.Controller = ((global::POFerro.Robotics.GameController.Proxy.Controller)(POFerro_Robotics_GameController_Controller_TO_POFerro_Robotics_GameController_Proxy_Controller(tmp)));
            }
            global::POFerro.Robotics.GameController.Axes tmp0 = from.Axes;
            if ((tmp0 != null)) {
                target.Axes = ((global::POFerro.Robotics.GameController.Proxy.Axes)(POFerro_Robotics_GameController_Axes_TO_POFerro_Robotics_GameController_Proxy_Axes(tmp0)));
            }
            global::POFerro.Robotics.GameController.Buttons tmp1 = from.Buttons;
            if ((tmp1 != null)) {
                target.Buttons = ((global::POFerro.Robotics.GameController.Proxy.Buttons)(POFerro_Robotics_GameController_Buttons_TO_POFerro_Robotics_GameController_Proxy_Buttons(tmp1)));
            }
            global::POFerro.Robotics.GameController.Sliders tmp2 = from.Sliders;
            if ((tmp2 != null)) {
                target.Sliders = ((global::POFerro.Robotics.GameController.Proxy.Sliders)(POFerro_Robotics_GameController_Sliders_TO_POFerro_Robotics_GameController_Proxy_Sliders(tmp2)));
            }
            global::POFerro.Robotics.GameController.PovHats tmp3 = from.PovHats;
            if ((tmp3 != null)) {
                target.PovHats = ((global::POFerro.Robotics.GameController.Proxy.PovHats)(POFerro_Robotics_GameController_PovHats_TO_POFerro_Robotics_GameController_Proxy_PovHats(tmp3)));
            }
            return target;
        }
        
        public static object POFerro_Robotics_GameController_Proxy_Controller_TO_POFerro_Robotics_GameController_Controller(object transformFrom) {
            global::POFerro.Robotics.GameController.Controller target = new global::POFerro.Robotics.GameController.Controller();
            global::POFerro.Robotics.GameController.Proxy.Controller from = ((global::POFerro.Robotics.GameController.Proxy.Controller)(transformFrom));
            target.TimeStamp = from.TimeStamp;
            target.Instance = from.Instance;
            target.Product = from.Product;
            target.InstanceName = from.InstanceName;
            target.ProductName = from.ProductName;
            target.Current = from.Current;
            return target;
        }
        
        public static object POFerro_Robotics_GameController_Controller_TO_POFerro_Robotics_GameController_Proxy_Controller(object transformFrom) {
            global::POFerro.Robotics.GameController.Proxy.Controller target = new global::POFerro.Robotics.GameController.Proxy.Controller();
            global::POFerro.Robotics.GameController.Controller from = ((global::POFerro.Robotics.GameController.Controller)(transformFrom));
            target.TimeStamp = from.TimeStamp;
            target.Instance = from.Instance;
            target.Product = from.Product;
            target.InstanceName = from.InstanceName;
            target.ProductName = from.ProductName;
            target.Current = from.Current;
            return target;
        }
        
        public static object POFerro_Robotics_GameController_Proxy_Axes_TO_POFerro_Robotics_GameController_Axes(object transformFrom) {
            global::POFerro.Robotics.GameController.Axes target = new global::POFerro.Robotics.GameController.Axes();
            global::POFerro.Robotics.GameController.Proxy.Axes from = ((global::POFerro.Robotics.GameController.Proxy.Axes)(transformFrom));
            target.TimeStamp = from.TimeStamp;
            target.X = from.X;
            target.Y = from.Y;
            target.Z = from.Z;
            target.Rx = from.Rx;
            target.Ry = from.Ry;
            target.Rz = from.Rz;
            return target;
        }
        
        public static object POFerro_Robotics_GameController_Axes_TO_POFerro_Robotics_GameController_Proxy_Axes(object transformFrom) {
            global::POFerro.Robotics.GameController.Proxy.Axes target = new global::POFerro.Robotics.GameController.Proxy.Axes();
            global::POFerro.Robotics.GameController.Axes from = ((global::POFerro.Robotics.GameController.Axes)(transformFrom));
            target.TimeStamp = from.TimeStamp;
            target.X = from.X;
            target.Y = from.Y;
            target.Z = from.Z;
            target.Rx = from.Rx;
            target.Ry = from.Ry;
            target.Rz = from.Rz;
            return target;
        }
        
        public static object POFerro_Robotics_GameController_Proxy_Buttons_TO_POFerro_Robotics_GameController_Buttons(object transformFrom) {
            global::POFerro.Robotics.GameController.Buttons target = new global::POFerro.Robotics.GameController.Buttons();
            global::POFerro.Robotics.GameController.Proxy.Buttons from = ((global::POFerro.Robotics.GameController.Proxy.Buttons)(transformFrom));
            target.TimeStamp = from.TimeStamp;
            if ((from.Pressed != null)) {
                int count = from.Pressed.Count;
                global::System.Collections.Generic.List<bool> tmp = new global::System.Collections.Generic.List<bool>(count);
                tmp.AddRange(from.Pressed);
                target.Pressed = tmp;
            }
            else {
                target.Pressed = null;
            }
            return target;
        }
        
        public static object POFerro_Robotics_GameController_Buttons_TO_POFerro_Robotics_GameController_Proxy_Buttons(object transformFrom) {
            global::POFerro.Robotics.GameController.Proxy.Buttons target = new global::POFerro.Robotics.GameController.Proxy.Buttons();
            global::POFerro.Robotics.GameController.Buttons from = ((global::POFerro.Robotics.GameController.Buttons)(transformFrom));
            target.TimeStamp = from.TimeStamp;
            global::System.Collections.Generic.List<bool> tmp = from.Pressed;
            if ((tmp != null)) {
                int count = tmp.Count;
                global::System.Collections.Generic.List<bool> tmp0 = new global::System.Collections.Generic.List<bool>(count);
                tmp0.AddRange(tmp);
                target.Pressed = tmp0;
            }
            return target;
        }
        
        public static object POFerro_Robotics_GameController_Proxy_Sliders_TO_POFerro_Robotics_GameController_Sliders(object transformFrom) {
            global::POFerro.Robotics.GameController.Sliders target = new global::POFerro.Robotics.GameController.Sliders();
            global::POFerro.Robotics.GameController.Proxy.Sliders from = ((global::POFerro.Robotics.GameController.Proxy.Sliders)(transformFrom));
            target.TimeStamp = from.TimeStamp;
            if ((from.Position != null)) {
                int count = from.Position.Count;
                global::System.Collections.Generic.List<int> tmp = new global::System.Collections.Generic.List<int>(count);
                tmp.AddRange(from.Position);
                target.Position = tmp;
            }
            else {
                target.Position = null;
            }
            return target;
        }
        
        public static object POFerro_Robotics_GameController_Sliders_TO_POFerro_Robotics_GameController_Proxy_Sliders(object transformFrom) {
            global::POFerro.Robotics.GameController.Proxy.Sliders target = new global::POFerro.Robotics.GameController.Proxy.Sliders();
            global::POFerro.Robotics.GameController.Sliders from = ((global::POFerro.Robotics.GameController.Sliders)(transformFrom));
            target.TimeStamp = from.TimeStamp;
            global::System.Collections.Generic.List<int> tmp = from.Position;
            if ((tmp != null)) {
                int count = tmp.Count;
                global::System.Collections.Generic.List<int> tmp0 = new global::System.Collections.Generic.List<int>(count);
                tmp0.AddRange(tmp);
                target.Position = tmp0;
            }
            return target;
        }
        
        public static object POFerro_Robotics_GameController_Proxy_PovHats_TO_POFerro_Robotics_GameController_PovHats(object transformFrom) {
            global::POFerro.Robotics.GameController.PovHats target = new global::POFerro.Robotics.GameController.PovHats();
            global::POFerro.Robotics.GameController.Proxy.PovHats from = ((global::POFerro.Robotics.GameController.Proxy.PovHats)(transformFrom));
            target.TimeStamp = from.TimeStamp;
            if ((from.Direction != null)) {
                int count = from.Direction.Count;
                global::System.Collections.Generic.List<int> tmp = new global::System.Collections.Generic.List<int>(count);
                tmp.AddRange(from.Direction);
                target.Direction = tmp;
            }
            else {
                target.Direction = null;
            }
            return target;
        }
        
        public static object POFerro_Robotics_GameController_PovHats_TO_POFerro_Robotics_GameController_Proxy_PovHats(object transformFrom) {
            global::POFerro.Robotics.GameController.Proxy.PovHats target = new global::POFerro.Robotics.GameController.Proxy.PovHats();
            global::POFerro.Robotics.GameController.PovHats from = ((global::POFerro.Robotics.GameController.PovHats)(transformFrom));
            target.TimeStamp = from.TimeStamp;
            global::System.Collections.Generic.List<int> tmp = from.Direction;
            if ((tmp != null)) {
                int count = tmp.Count;
                global::System.Collections.Generic.List<int> tmp0 = new global::System.Collections.Generic.List<int>(count);
                tmp0.AddRange(tmp);
                target.Direction = tmp0;
            }
            return target;
        }
    }
}
